import type {
  ActivityEntry,
  Blocker,
  IsoDate,
  JobFailure,
  LanguageCode,
  LanguageTrack,
  PipelineStage,
  Priority,
  ResearchRecord,
  ReviewCheckItem,
  ReviewState,
  SourceType,
  TrackStepStatus,
  VideoFormat,
  VideoProject,
} from '@/types';
import { PIPELINE_STAGES } from '@/types';
import { CHANNELS_BY_ID } from './channels';
import { addDays, isoDateTime } from '@/lib/date';
import { hashString, seededRandom } from '@/lib/utils';

/** Compact seed row. The builder expands it into a full `VideoProject`. */
export interface ProjectSeed {
  id: string;
  channelId: string;
  title: string;
  format: VideoFormat;
  stage: PipelineStage;
  priority: Priority;
  languages: LanguageCode[];
  durationMinutes: number;
  /** Days from the demo anchor date; negative is in the past. */
  dueInDays: number;
  estimatedCost: number;
  hook: string;
  summary: string;
  angle: string;
  keywords: string[];
  callToAction: string;
  research?: SeedResearch[];
  blocker?: Blocker;
  failure?: JobFailure;
  /** Days from the anchor for the publish slot; defaults sensibly per stage. */
  slotInDays?: number;
  playlist: string;
  /** Overrides the derived readiness for one language, e.g. a lagging Hindi track. */
  trackOverrides?: Partial<Record<LanguageCode, Partial<Omit<LanguageTrack, 'language'>>>>;
}

export interface SeedResearch {
  title: string;
  sourceName: string;
  sourceUrl: string;
  sourceType: SourceType;
  /** Days from the anchor, or `null` for a source nobody has verified yet. */
  verifiedInDays: number | null;
  verifiedBy?: string;
  claims: string[];
  credibility: 'high' | 'medium' | 'low';
  notes?: string;
}

export const STAGE_INDEX: Record<PipelineStage, number> = Object.fromEntries(
  PIPELINE_STAGES.map((stage, index) => [stage, index]),
) as Record<PipelineStage, number>;

const REVIEWERS = ['Priya Nair', 'Arjun Mehta', 'Sana Qureshi', 'Rahul Deshpande'];
const PRODUCERS = ['Meera Iyer', 'Vikram Shah', 'Aditi Roy', 'Karan Bose'];

/**
 * A step's readiness follows the project's stage: anything before the current
 * stage is done, the current stage is in progress, anything after has not
 * started. Non-primary languages lag by one step, which is how a real
 * bilingual pipeline behaves.
 */
function stepStatus(stage: PipelineStage, step: PipelineStage, lagging: boolean): TrackStepStatus {
  const current = STAGE_INDEX[stage];
  const target = STAGE_INDEX[step];
  if (current > target) return lagging && current === target + 1 ? 'in_progress' : 'ready';
  if (current === target) return lagging ? 'not_started' : 'in_progress';
  return 'not_started';
}

function buildTrack(
  seed: ProjectSeed,
  language: LanguageCode,
  anchor: IsoDate,
  random: () => number,
): LanguageTrack {
  const channel = CHANNELS_BY_ID[seed.channelId];
  const lagging = language !== channel.config.primaryLanguage;
  const wordsPerMinute = language === 'hi' ? 132 : 148;
  const script = stepStatus(seed.stage, 'script', lagging);
  const audio = stepStatus(seed.stage, 'audio', lagging);
  const captions = stepStatus(seed.stage, 'editing', lagging);
  const drafted = script !== 'not_started';

  const base: LanguageTrack = {
    language,
    script,
    audio,
    captions,
    scriptWordCount: drafted
      ? Math.round(seed.durationMinutes * wordsPerMinute * (0.9 + random() * 0.2))
      : 0,
    scriptBody: drafted ? scriptBody(seed, language) : '',
    publishTitle: publishTitle(seed, language),
    publishDescription: publishDescription(seed, language, channel.name),
    updatedAt: isoDateTime(addDays(anchor, -Math.floor(random() * 9) - 1), '14:20'),
  };

  return { ...base, ...seed.trackOverrides?.[language] };
}

function publishTitle(seed: ProjectSeed, language: LanguageCode): string {
  return language === 'hi' ? `${seed.title} (हिंदी)` : seed.title;
}

function publishDescription(seed: ProjectSeed, language: LanguageCode, channelName: string): string {
  const intro = language === 'hi' ? 'इस वीडियो में:' : 'In this video:';
  return `${intro} ${seed.summary}\n\n${seed.callToAction}\n\n— ${channelName}\n\n#${seed.keywords
    .slice(0, 4)
    .map((keyword) => keyword.replace(/\s+/g, ''))
    .join(' #')}`;
}

/**
 * A short readable draft so the Script tab has something real to edit. It is
 * assembled from the brief — nothing here was generated by a model.
 */
function scriptBody(seed: ProjectSeed, language: LanguageCode): string {
  if (language === 'hi') {
    return [
      `[कोल्ड ओपन — 0:00]`,
      seed.hook,
      ``,
      `[परिचय — 0:20]`,
      seed.summary,
      ``,
      `[मुख्य भाग — 1:10]`,
      `${seed.angle} इस हिस्से में हम एक-एक करके हर बिंदु पर आते हैं, और स्क्रीन पर वही दिखाते हैं जिसकी बात हो रही है।`,
      ``,
      `[समापन — ${Math.max(2, seed.durationMinutes - 1)}:00]`,
      seed.callToAction,
    ].join('\n');
  }
  return [
    `[COLD OPEN — 0:00]`,
    seed.hook,
    ``,
    `[SET-UP — 0:20]`,
    seed.summary,
    ``,
    `[MAIN BODY — 1:10]`,
    `${seed.angle} We take each point in turn and keep the relevant evidence on screen while it is being discussed.`,
    ``,
    `[CLOSE — ${Math.max(2, seed.durationMinutes - 1)}:00]`,
    seed.callToAction,
  ].join('\n');
}

function buildResearch(seed: ProjectSeed, anchor: IsoDate): ResearchRecord[] {
  return (seed.research ?? []).map((item, index) => ({
    id: `${seed.id}_res_${index + 1}`,
    title: item.title,
    sourceUrl: item.sourceUrl,
    sourceName: item.sourceName,
    sourceType: item.sourceType,
    verifiedOn: item.verifiedInDays === null ? null : addDays(anchor, item.verifiedInDays),
    verifiedBy: item.verifiedInDays === null ? null : (item.verifiedBy ?? REVIEWERS[index % REVIEWERS.length]),
    claimsSupported: item.claims,
    credibility: item.credibility,
    notes: item.notes,
    addedOn: addDays(anchor, (item.verifiedInDays ?? -4) - 2),
  }));
}

function buildChecklist(seed: ProjectSeed, complete: boolean): ReviewCheckItem[] {
  const channel = CHANNELS_BY_ID[seed.channelId];
  const items: ReviewCheckItem[] = [
    { id: `${seed.id}_chk_sources`, label: 'Every factual claim is backed by a verified source', checked: complete, required: true },
    { id: `${seed.id}_chk_rules`, label: 'Script follows the channel editorial rules', checked: complete, required: true },
    { id: `${seed.id}_chk_titles`, label: 'Title and description match the actual content', checked: complete, required: true },
    { id: `${seed.id}_chk_captions`, label: 'Captions checked for both language tracks', checked: complete, required: false },
    { id: `${seed.id}_chk_licence`, label: 'All visuals and audio carry a usable licence', checked: complete, required: true },
  ];
  if (channel.audienceRating === 'family') {
    items.push({ id: `${seed.id}_chk_kids`, label: 'Marked "Made for Kids"; no peril, no loud cuts', checked: complete, required: true });
  }
  if (channel.audienceRating === 'mature') {
    items.push({ id: `${seed.id}_chk_adult`, label: 'Age restriction applied; clinical language throughout', checked: complete, required: true });
  }
  return items;
}

function buildReview(seed: ProjectSeed, anchor: IsoDate, random: () => number): ReviewState {
  const index = STAGE_INDEX[seed.stage];
  const reviewIndex = STAGE_INDEX.review;
  const reviewer = REVIEWERS[Math.floor(random() * REVIEWERS.length)];

  if (index > reviewIndex) {
    return {
      decision: 'approved',
      reviewer,
      reviewedAt: isoDateTime(addDays(anchor, -Math.floor(random() * 10) - 2), '11:05'),
      checklist: buildChecklist(seed, true),
      notes: 'Approved. Sources check out and the close lands cleanly.',
    };
  }
  if (index === reviewIndex) {
    const changes = seed.blocker?.reason === 'script_rewrite' || seed.priority === 'urgent';
    return {
      decision: changes ? 'changes_requested' : 'pending',
      reviewer: changes ? reviewer : null,
      reviewedAt: changes ? isoDateTime(addDays(anchor, -1), '16:40') : null,
      checklist: buildChecklist(seed, false),
      notes: changes
        ? 'Second half drifts from the brief. Tighten the middle section and re-check the two unverified sources.'
        : '',
    };
  }
  return { decision: 'pending', reviewer: null, reviewedAt: null, checklist: buildChecklist(seed, false), notes: '' };
}

function buildActivity(seed: ProjectSeed, anchor: IsoDate, random: () => number): ActivityEntry[] {
  const producer = PRODUCERS[Math.floor(random() * PRODUCERS.length)];
  const entries: ActivityEntry[] = [
    {
      id: `${seed.id}_act_1`,
      at: isoDateTime(addDays(anchor, -Math.floor(random() * 20) - 12), '09:15'),
      actor: producer,
      message: 'Project created from a channel content idea.',
    },
  ];
  const reached = PIPELINE_STAGES.slice(1, STAGE_INDEX[seed.stage] + 1);
  reached.forEach((stage, index) => {
    entries.push({
      id: `${seed.id}_act_${index + 2}`,
      at: isoDateTime(addDays(anchor, -Math.max(1, 11 - index * 2)), '10:30'),
      actor: index % 2 === 0 ? producer : REVIEWERS[index % REVIEWERS.length],
      message: `Moved to ${stage.charAt(0).toUpperCase()}${stage.slice(1)}.`,
    });
  });
  if (seed.blocker) {
    entries.push({
      id: `${seed.id}_act_blocked`,
      at: isoDateTime(seed.blocker.since, '12:00'),
      actor: REVIEWERS[0],
      message: `Flagged as blocked: ${seed.blocker.note}`,
    });
  }
  if (seed.failure) {
    entries.push({
      id: `${seed.id}_act_failed`,
      at: seed.failure.failedAt,
      actor: 'Pipeline runner (simulated)',
      message: `${seed.failure.step} job failed: ${seed.failure.message}`,
    });
  }
  return entries.sort((a, b) => b.at.localeCompare(a.at));
}

export function buildProject(seed: ProjectSeed, anchor: IsoDate): VideoProject {
  const random = seededRandom(hashString(seed.id));
  const channel = CHANNELS_BY_ID[seed.channelId];
  const index = STAGE_INDEX[seed.stage];
  const dueDate = addDays(anchor, seed.dueInDays);
  const slotDay = addDays(anchor, seed.slotInDays ?? seed.dueInDays);

  const scheduled = seed.stage === 'scheduled';
  const published = seed.stage === 'published';

  return {
    id: seed.id,
    channelId: seed.channelId,
    title: seed.title,
    format: seed.format,
    stage: seed.stage,
    priority: seed.priority,
    languages: seed.languages,
    tracks: seed.languages.map((language) => buildTrack(seed, language, anchor, random)),
    targetDurationMinutes: seed.durationMinutes,
    dueDate,
    estimatedCost: seed.estimatedCost,
    actualCost: published ? Math.round(seed.estimatedCost * (0.88 + random() * 0.3)) : null,
    brief: {
      hook: seed.hook,
      summary: seed.summary,
      audience: channel.config.audience,
      angle: seed.angle,
      keywords: seed.keywords,
      callToAction: seed.callToAction,
    },
    research: buildResearch(seed, anchor),
    review: buildReview(seed, anchor, random),
    publishing: {
      visibility: channel.audienceRating === 'mature' ? 'unlisted' : 'public',
      playlist: seed.playlist,
      tags: seed.keywords,
      scheduledFor: scheduled || published ? isoDateTime(slotDay, channel.config.cadence.publishTime) : null,
      publishedAt: published ? isoDateTime(slotDay, channel.config.cadence.publishTime) : null,
      youtubeVideoId: null,
      thumbnailAssetId: index >= STAGE_INDEX.visuals ? `as_${seed.id}_thumb` : null,
      madeForKids: channel.audienceRating === 'family',
    },
    assetIds: [],
    blocker: seed.blocker ?? null,
    failure: seed.failure ?? null,
    activity: buildActivity(seed, anchor, random),
    createdAt: isoDateTime(addDays(anchor, -Math.floor(random() * 20) - 12), '09:15'),
    updatedAt: isoDateTime(addDays(anchor, -Math.floor(random() * 5) - 1), '17:45'),
  };
}
